### ISSUE TITLE
Missing directories in template app gives error when compiling on MacOS.

### ISSUE THREAD

**Issue by jwpyle3** [fvdhoef/aquarius-plus#13]
I downloaded and tried compiling the emulator.  I was was getting an error when the Makefile tried to copies files to the missing directories.

Under /aquarius-plus/System/emulator/macos/AquariusPlusEmu.app/Contents

I created two directories MacOS and Resources

Also, since I didn't like not having an icon I created one called AquariusPlusEmu.icns (as listed in the .plist file) and added it to the Resources directory. 

After doing this it the build completed successfully.

**Comment by fvdhoef** [comment]
Thanks for reporting this. Git doesn't commit empty directories. So I will change the makefile to create the missing directory. Can you share the icon you made, then I will include it in the repository?

**Comment by jwpyle3** [comment]
[AquariusPlusEmu.icns.zip](https://github.com/fvdhoef/aquarius-plus/files/12063399/AquariusPlusEmu.icns.zip)

Had to zip it.

**Comment by fvdhoef** [comment]
Thank you! I've added it to the repo and fixed the issue.
