### ISSUE TITLE
Correction and addition for "SDK: Getting started on MacOS" page.

### ISSUE THREAD

**Issue by jwpyle3** [fvdhoef/aquarius-plus#26]
On the Mac to start the build process it should be COMMAND + SHIFT + B instead of CONTROL + SHIFT + B

On newer Macs they don't default to Bash, they are using ZSH.   Can you add that if the user's default shell is ZSH they should put the 'export' lines in .zshrc file?  That is where I had to put mine as I don't have a .bashrc file.

**Comment by fvdhoef** [comment]
Thanks! I've corrected the wiki.
