### ISSUE TITLE
Fixed Mac icon size and updated the 'plus' to match the actual Aquarius+ Logo

### ISSUE THREAD

**Issue by jwpyle3** [fvdhoef/aquarius-plus#28]
I fixed the Mac icon size to match Mac App icons.  I had selected iOS size before which make the icon bigger than the others when on the Mac dock.  I also updated the 'plus' to better match the actual logo.

I have also included the updated Windows .ico file.  This one matches what Microsoft recommends with a transparent background.  I have included the original PNG in case you would like to add back the white background.  

[AquariusPlusEmu_icons.zip](https://github.com/fvdhoef/aquarius-plus/files/12414951/AquariusPlusEmu_icons.zip)

**Comment by fvdhoef** [comment]
Thank you. I need to check if the windows icon will be visible enough. It might needs the white outline on the whole icon (not just the '+').

**Comment by fvdhoef** [comment]
Ok, I checked on Windows. Looks fine! Thanks again.
