### ISSUE TITLE
AD&D Rom Doesn't Respond to Arrow Keys Properly

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#30]
AD&D ROM cart image doesn't process arrow keys the same way the hand controller does. UPLR arrows give low beeps rather than move the character through the maze. Tested on V0.13a and V0.14b with same results.

**Comment by RevCurtisP** [comment]
Verified that cursor keys emulate hand controller when scroll lock is on and described behavior happens when scroll lock is on.

**Comment by fvdhoef** [comment]
Fixed.
