### ISSUE TITLE
Question or Suggestion: File associations to emulator.

### ISSUE THREAD

**Issue by jwpyle3** [fvdhoef/aquarius-plus#31]
I was wondering if in the future the emulator would be able to RUN a CAQ or ROM file if it was clicked in the OS.  

I created two icons that I use on my system (Mac) that makes the CAQ files look like a Cassette and ROM files look like the Aquarius Cartridge.  The only issue I found was that other emulators that I have on my system, i.e. Stella (Atari 2600 emulator) assigns their icon to ROM files.  To resolve that on mine I renamed to RAQ (ROM for Aquarius), but then they won't work.  I haven't looked through the code yet to see what changes I would need to make RAQ work like ROM files.

I modified the Info.plist file to automatically assign the icons to the CAQ and ROM files on my system.  

I have also included Windows .ico files but not sure if they could be added from the .msi installer.  

This is just a future maybe.
[Aquarius Icons.zip](https://github.com/fvdhoef/aquarius-plus/files/12588263/Aquarius.Icons.zip)

**Comment by fvdhoef** [comment]
That is a nice idea. I'm not sure how the OS passes the filename to the executable. If it is passed as an argument to the main function (or WinMain on windows) or that is using some other mechanism. I have to look into it.

**Comment by fvdhoef** [comment]
I'm going to close this issue for now. If someone wants to implement this, a pull request can be made.
