### ISSUE TITLE
"? Unknown error" when trying to run "esp:settings.aqx"

### ISSUE THREAD

**Issue by jwpyle3** [fvdhoef/aquarius-plus#34]
I was going to update to V0.17a from V0.17 so I entered RUN "esp:settings.aqx".  When I hit enter I received the "? Unknown error". Tried rebooting the Aquarius+ unit and completely powering off the unit with the same results.

I was able to update V0.17a by copying the settings program from GitHub to the sd card and running it from there.

Tried RUN "esp:settings.aqx" after updating and it still returned the same message.

I also tried it will the .caq extension just in case.

**Comment by RevCurtisP** [comment]
The settings programs is now "esp:settings" with no extension,

RUN "esp:settings"
