### ISSUE TITLE
BASIC sprite data is not cleared after reset (emulator/physical)

### ISSUE THREAD

**Issue by MattPilz** [fvdhoef/aquarius-plus#35]
(Tested on 0.17a)

When defining sprites, their data persists even after running "NEW" command or CTRL+ESC to reset BASIC (including System → Reset Aquarius+ in emulator).

Example code (spritetest.baq):

```
10 CLS:SCREEN 4
20 SET TILE 0 TO $"12345678"
30 DEF SPRITE S$ = 0,0,0
40 DEF TILELIST T$ = 0
50 DEF ATTRLIST A$ = 0
60 SET SPRITE S$ TILE T$ ATTR A$
70 SET SPRITE S$ POS 100,100 ON
RUN
```

After reset, type SCREEN 4 (or SCREEN 3) and you will see the sprite data persists. I would expect a reset to do a memory wipe including all sprite data.

[spritetest.zip](https://github.com/fvdhoef/aquarius-plus/files/12702825/spritetest.zip)

**Comment by RevCurtisP** [comment]
Fixed in current release of plusBASIC, available at https://github.com/RevCurtisP/AquariusPlus/tree/main/plusBasic/zout/aquarius,rom
plusBASIC dev releases happen frequently, so it's best to always download the latest rom and try it, to make sure the problem hasn't already been addressed
