### ISSUE TITLE
minidiag.rom fails with error: Test result defective function possible damaged parts

### ISSUE THREAD

**Issue by timduarte** [fvdhoef/aquarius-plus#37]
I ran minidiag.rom and I get the following error:

Test result defective function 
possible damaged parts 
processor halt 
check halt light 
press reset to restart

this appears after I skip the 2 controller tests

 I was able to run the games Tetris and Burger time. 

But I do not have any controllers.  so I could not play

trying to map my xbox one controller but not having luck with that.
I opened a separate issue for that.

thank you for your help!

**Comment by RevCurtisP** [comment]
I ran minidiag.rom on hardware Aq+ with System V0.17c plusBASIC v0.12g
Did not get "Test result defective function, possible damaged parts"
Message "processor halt. check halt light. press reset to restart" is normal.

I suspect that the first message may be correct and there is a hardware error.

**Comment by fvdhoef** [comment]
The diag rom always shows "Defective function" and "Possible damaged parts". These are just the headings of a 2-column table. As long as nothing is mentioned belowed these headings it is fine. Also the processor halt is normal.

BTW You can emulate a handcontroller with your keyboard by pressing the scroll lock key. After enabling scroll lock, your cursor keys and F1-F6 will function as a hand controller.

**Comment by timduarte** [comment]
I tried a wired USB keyboard and I could visibly see the scroll lock light up and I was able to use the cursor keys and the F1-F6 keys and it showed correctly in the minidiag.rom when I ran it.  Still saw the error

Test result defective function
possible damaged parts
processor halt
check halt light
press reset to restart

But I am not concerned about it especially after you state this is normal. So please feel free to close this issue. I am all set. thank you for your help.
