### ISSUE TITLE
Emulator runs too fast

### ISSUE THREAD

**Issue by MackW** [fvdhoef/aquarius-plus#43]
Emulator seems to run too fast on speed x1 (might be NTSC vs PAL)
not sure if it's the emulator or the VBL on port $FD (which is what it's synced on for speed)
This is noticed by my demo RFDV7.rom when the music etc is playing.
I'll write a little timing loop to check the frame length and will add details here

**Comment by RevCurtisP** [comment]
VBLANK is 60hz on NTSC and 50hz on PAL so NTSC will run fast.

**Comment by MackW** [comment]
Doesn't seem any way to change to 50hz though?

**Comment by fvdhoef** [comment]
The Aq+ is a 60Hz only system, since we're outputting to VGA.

**Comment by MackW** [comment]
Bahh,,, lol.  
Will need to put timing detection code in then,  Ah well good to know for future, so that I can make stuff compatible
