### ISSUE TITLE
Border effects don't work in the Emu

### ISSUE THREAD

**Issue by MackW** [fvdhoef/aquarius-plus#44]
RFDV7.rom does some border effects based off the VBL on port $FD
The emu doesn't seem to handle these - Aqualite does (Virt Aquarius doesnt)

**Comment by fvdhoef** [comment]
I don't have access to a real Aquarius and as such I've not been able to measure the exact frame timing. Also the emulator is only emulating line by line.

**Comment by MackW** [comment]
at a guess, - you are taking the border colour at frame start, and then not updating it through the frame (as virt aquarius does).
Aqualite does a cycle count, so that it knows where it is on the border. 
It's the same stuff as what was done on the speccy, changing border colour mid frame gave a split.
![image](https://github.com/fvdhoef/aquarius-plus/assets/6732183/78bef568-4b17-4bc3-877c-e3bb29564f7e)
is how it should look

**Comment by MackW** [comment]
I can do the frame timings for you if it helps ?

**Comment by fvdhoef** [comment]
The border color/character is read every line rendered in the emulator. On the actual hardware it is read at the start of each border character.

**Comment by MackW** [comment]
Sean's just posted a vid that the border is behaving the same for both the emu and HW versions. 

https://github.com/fvdhoef/aquarius-plus/assets/6732183/f77dcb90-d627-462d-af32-df730b0bb55c

**Comment by MackW** [comment]
Border should be Black until the top row, then red and red until 1px of the border at the bottom

**Comment by fvdhoef** [comment]
It probably then has more to do with the behaviour of port $FD.
The value in there currently is: 1 for lines < 242, otherwise 0

**Comment by MackW** [comment]
Ahh, the value on the real hardware is actually 0 between lines 0->25 char lines ..
need to check the values, but $FD is still 0 until the first Char display line starts

**Comment by fvdhoef** [comment]
If you can describe me the correct behaviour that would be great! Then I can fix it.

**Comment by MackW** [comment]
Let me find the stuff I gave Richard for when he did Aqualite.

**Comment by MackW** [comment]
Lol... possibly a little simplistic, but corrrect
![image](https://github.com/fvdhoef/aquarius-plus/assets/6732183/594f1e09-9d77-4765-b66d-cf8cf0b0a5c6)

**Comment by fvdhoef** [comment]
So the value is already low in the border?

**Comment by MackW** [comment]
Yes, it goes low at the first line of the border at the bottom of the screen, and stays low until first line of the top drawn screen
100% - active area - you got it

**Comment by fvdhoef** [comment]
Can you give me the RFDV7.rom so I can test with that?

**Comment by MackW** [comment]
Zip file of the ROM in question for archive 
[RFDV7.zip](https://github.com/fvdhoef/aquarius-plus/files/13064015/RFDV7.zip)

**Comment by fvdhoef** [comment]
Fixed in emulator commit ee99189d5e8cc2a49688887c626fd5c486a40fcb and FPGA commit 36576eb7472c257a5f3b22f93ffcab3909fb0dee

**Comment by fvdhoef** [comment]
Thanks Mack to help with this!
