### ISSUE TITLE
CP/M Filenames

### ISSUE THREAD

**Issue by LoudScotsBloke** [fvdhoef/aquarius-plus#46]
If you copy standard CP/M .com files on to the SD Card in UPPERCASE, the Aquarius can not see them via AQDIR or AQCOPY. You have to rename the files to lowercase before you can see them within Aquarius CP/M. I have attached a couple of screen shots showing this. Note that the renamed lower case catchum.com and catchu.dat are seen, but the LADDER.COM and LADDER.DAT are not. This was the case with CATCHUM.COM and CATCHUM.DAT until renamed to lower case.
![IMG20231029154115](https://github.com/fvdhoef/aquarius-plus/assets/38511341/487e5751-a2d6-478c-be06-7716f9bab112)
![IMG20231029154052](https://github.com/fvdhoef/aquarius-plus/assets/38511341/ce98ddad-9756-4dff-83ef-5301f0b98937)

**Comment by fvdhoef** [comment]
Fixed in V0.20a
