### ISSUE TITLE
Linux Emulator unable to save

### ISSUE THREAD

**Issue by LoudScotsBloke** [fvdhoef/aquarius-plus#47]
Unable to save from the Linux version of the Emulator. Screen shot showing issue.
![Screenshot from 2023-10-29 21-18-40](https://github.com/fvdhoef/aquarius-plus/assets/38511341/ca547471-c046-40c2-b70f-a637e890ebeb)

**Comment by fvdhoef** [comment]
Did you select a SD card directory as shown in the following image (next to Eject SD card)?
<img width="483" alt="Scherm­afbeelding 2023-10-30 om 07 07 42" src="https://github.com/fvdhoef/aquarius-plus/assets/48173585/1fe36aef-a0f5-4e1b-b15d-02eeae9e370c">
If not, use the 'Select SD card directory...' option to select one.
