### ISSUE TITLE
Cannot CALL 0 (reset) after performing SET FAST ON

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#51]
In Immediate mode, I can't CALL 0 to reset after I've done a SET FAST ON.

If I do SET FAST ON then do SET FAST OFF before the CALL 0, it resets properly.

**Comment by RevCurtisP** [comment]
Reproduced results on hardware v0,20 and v0.20b
When bit 2 of port $FB is set, after issuing CALL 0, the system stops resonding.

In emulator, CALL 0 executes correctly with the bit set or reset.

**Comment by RevCurtisP** [comment]
**Fixed as of v0.16f**

**Cause:** In turbo mode, ESP_KEYMODE was being called before ESP_RESET had completed.

**Solution:** Modified ROM _reset routine to always start with turbo disabled.
