### ISSUE TITLE
Cursor keys not generating ASCII characters in emulator

### ISSUE THREAD

**Issue by RevCurtisP** [fvdhoef/aquarius-plus#52]
In System V0.20 and V0.20b emulator the cursor keys are mapped to the controller regardless of scroll lock status.

**Comment by RevCurtisP** [comment]
Likewise, F1 through F6 are always mapped to controller in emulator.

**Comment by fvdhoef** [comment]
<img width="401" alt="image" src="https://github.com/fvdhoef/aquarius-plus/assets/48173585/a2873a2d-c90b-4e40-b9e9-2a95f5f0db98">
Did you uncheck the option from the menu?

**Comment by RevCurtisP** [comment]
The above option was, in fact, checked, Keys work as expected after unchecking.
