### ISSUE TITLE
Latest V0.21 doesnt run any of my .ROM games

### ISSUE THREAD

**Issue by LoudScotsBloke** [fvdhoef/aquarius-plus#54]
![Screenshot from 2023-11-12 20-57-50](https://github.com/fvdhoef/aquarius-plus/assets/38511341/09f80767-a087-4463-b1e7-38292e26c348)
![Screenshot from 2023-11-12 20-59-06](https://github.com/fvdhoef/aquarius-plus/assets/38511341/a17bae6c-ddf5-4570-bdf0-3ca5e5e586c6)
![Screenshot from 2023-11-12 21-03-33](https://github.com/fvdhoef/aquarius-plus/assets/38511341/7d3c8b1b-22a5-44c6-9187-dd5f997d1a5a)

This is on both the real hardware and on the Emulator. I have loaded all my games on previous versions ok. CAQ files seem unaffected, but .ROM files fill the screen with £'s and then reboot.

**Comment by RevCurtisP** [comment]
Do the ROM files that come with the emulator "sdcard/roms" run okay?

**Comment by LoudScotsBloke** [comment]
I have just tried a couple, and they seem ok yes

**Comment by LoudScotsBloke** [comment]
Just seems to be my games :( but they worked on Version 20c and previous versions.

**Comment by RevCurtisP** [comment]
I will need one of the ROM images to troubleshoot.

**Comment by LoudScotsBloke** [comment]
They are on the latest AquariusPlus SD download

**Comment by LoudScotsBloke** [comment]
Any update on this guy's?

**Comment by fvdhoef** [comment]
Tested on V0.23 and is working now.
