### ISSUE TITLE
ON ERROR GOTO works on alternate attempts.

### ISSUE THREAD

**Issue by jaymundy** [fvdhoef/aquarius-plus#55]
ON ERROR GOTO operation seems to work only every alternate attempt. When you run this multiple times it alternates between printing "MY BAD" and giving a divide by zero message.

100 ON ERROR GOTO 500
200 PRINT 4/0
300 STOP
500 PRINT "MY BAD"

**Comment by RevCurtisP** [comment]
Fixed in v0.18r
