### ISSUE TITLE
Can't Run AQDS.AQX on a V0.22 + v0.18 System

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#56]
On my system running V0.22 OS and v0.18 pB, when I get into the aqds folder, and RUN "AQDS.AQX" it shows

Ok
run
Ok
aqds/fileman.bin

Not sure what to do. Runs fine on other systems upgraded to V0.22 via esp:settings > updategh > V0.22

**Comment by 1stage** [comment]
https://github.com/fvdhoef/aquarius-plus/assets/20803301/35ab7edd-f0c7-4662-9a68-a7bc70f21018

**Comment by fvdhoef** [comment]
Did you update the system that shows the weird behaviour on DevStudio also via updategh?
Is this the first rev2 board (the same one I have)? Maybe there is some hardware issue? For example the banking pins? (high address lines of the RAM)
DevStudio is running from page 40-44

**Comment by 1stage** [comment]
Yes, it was via an updategh.

It is the WHITE prototype board which you and I have (and a few others). When I opened the case to try a USB-BASED update, the SD card reader game loose from the side mounts, so I have to fix that as well now. I'll check the RAM pins all around when I do this.

**Comment by fvdhoef** [comment]
Any update on this?

**Comment by 1stage** [comment]
This motherboard seems to have issues. I've reflowed the chips, but the system could not recover from an updategh.

I will USB upload the image again and report back.
