### ISSUE TITLE
ESP32 SEEK command not returning a result code.

### ISSUE THREAD

**Issue by RevCurtisP** [fvdhoef/aquarius-plus#57]
After issuing the command $14 and the 4-byte file position, my code is waiting for a return code as specified in the documentation, no return code is ever received. The file position is being changed as expected.

**Comment by fvdhoef** [comment]
Can you please compare your code with https://github.com/fvdhoef/aquarius-plus/blob/master/SDK/asm/projects/cpm/bios.inc#L705 ?
CP/M is using SEEK extensively and it is working fine there.

The command is $14, then the file descriptor, then the 4 byte file position.
Maybe you forget to send the file descriptor?

**Comment by RevCurtisP** [comment]
I looked at the code again and it is getting a result.
