### ISSUE TITLE
Charrom glitches on hardware when using "widescreen" mode

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#60]
On hardware, running OS V0.22c in "widescreen" mode (force uploaded pB v0.19f), I get charrom glitches as I toggle between new and old character sets (CTRL + N and CTRL + O)

**Comment by 1stage** [comment]
The charrom glitching doesn't happen in "narrow" mode.

**Comment by 1stage** [comment]
Confirmed it happens on multiple systems with same configuration. Not specific to the original system discovered on.

**Comment by fvdhoef** [comment]
Thanks Sean for reporting! I found the issue and making a fix for it.
