### ISSUE TITLE
GETPALETTE$ doesn't work (crashes) in pB v0.19t

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#62]
When running /demos/mandelbrot/mandelbrot.baq, the system crashes when GETPALETTE$(0) is called in line 1010.

**Comment by 1stage** [comment]
Works in earlier pB v0.19h / OS V0.22f.

**Comment by fvdhoef** [comment]
Tested on release V0.23 / pb v0.20 and is working now.
