### ISSUE TITLE
UPDATEGH is giving update failed error (again)

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#74]
Using V0.26, running esp:settings, checked WiFi (running), and can't UPDATEGH to V0.27 (either default ENTER or manually entering "V0.27").

Also noticed by another user on FB group

**Comment by fvdhoef** [comment]
Ok, seems that updategh is broken again. Github has changed some of its certificates again. The github webpages are using a USERTrust root certificate, but the downloads are now served by DigiCert Global Root G2 (We already has DigiCert Global Root CA, but they changed that to the G2 variant). I have now added a few extra root certificates to the firmware. Hopefully updategh it will now keep working for longer.
