### ISSUE TITLE
Running Win emulator V0.32 and Running demos/ISS-Map/run-me.bas Produces Occasional Disk I/O errors

### ISSUE THREAD

**Issue by 1stage** [fvdhoef/aquarius-plus#76]
While running the newest ISS-Map demo, it will usually run fine, but will occasionally get a "Disk I/O error" when running the main loop to re-pull the ISS-Map json data.

I will test on real hardware when I get home this evening.

**Comment by 1stage** [comment]
Confirmed same behavior on HW

**Comment by 1stage** [comment]
For hardware, in programs that make frequent http:// requests, eventually, a Disk I/O error is generated. Problem resets itself at a power cycle.

For the Windows emulator, the problem also eventually occurs as well. If the Disk I/O error isn't generated, then often the emulator becomes "frozen" or non-responsive. The whole system seems to start having issues, even if the emulator is quit. Only a system reboot seems to correct it.

**Comment by RevCurtisP** [comment]
Testing: Verified that the LOAD command closes the file handle when the load is complete, and the ESP32 info debug window in the emulator shows no files open between requests.

**Comment by RevCurtisP** [comment]
Testing with `http://aquarius.plus/api/datetime.php`
 - Over 1,000 HTTP requests with 0 errors in emulator.
 - Over  600 HTTP requests with 2 Disk I/O errors on hardware.
 
The Disk I/O Errors are most likely error responses from the server due to it being hammered with requests.
