### ISSUE TITLE
Undefined line number error

### ISSUE THREAD

**Issue by LoudScotsBloke** [fvdhoef/aquarius-plus#77]
You get an '**Undefined line number error**' when loading a raw TXT file (source code) if your line numbers are out of sequence. I admit that my code can jump around a bit when I am in mid-development, and I tend to have sections of code that dont follow the line number sequence during dev. I then pull it all together for the production versions, but during dev and test, I rely on the Aquarius to sort the line numbering. For example..

10 rem some stuff
20 rem some more stuff
3 cls
4 poke some stuff
100 print
85 print

![IMG20240612210051](https://github.com/fvdhoef/aquarius-plus/assets/38511341/631d7268-4d45-49b7-a7f2-d239196f470d)

**Comment by RevCurtisP** [comment]
LOADing a program in ASCII format requires the line numbers to be an order with no duplications. There are multiple reasons for this, and it will not change.
