### ISSUE TITLE
Feature request - ESP command to read entire game controller state

### ISSUE THREAD

**Issue by RevCurtisP** [fvdhoef/aquarius-plus#78]
Requested by Mack Wharton

Suggested format

ESP_GETJOYSTICK

- Request
  - Command byte
  - Controller ID (for future expansion)
- Response
  - Result (0/ERR_NOT_FOUND) 
  - Controller state (multiple bytes)

**Comment by fvdhoef** [comment]
Implemented in release V0.33. See https://github.com/fvdhoef/aquarius-plus/wiki/TRM%3A-ESP32-interface#getgamectrl for ESP command.
