### ISSUE TITLE
PLAYPT3 seems to stop randomly

### ISSUE THREAD

**Issue by LoudScotsBloke** [fvdhoef/aquarius-plus#79]
Thought I would have a play with PLAYPT3 on my latest game, and the song seems to stop at random time intervals, even without any program loaded or running. Currently using system V0.33 and plusBASIC v0.22x

**Comment by RevCurtisP** [comment]
- Emulator, hardware, or both?
- Is there a specific .pt3 file this is happening with?
- Does it stop entirely, or pause then continue/restart?
- After it stops will RESUME PT3 cause it to continue where it left off?

**Comment by LoudScotsBloke** [comment]
> * Emulator, hardware, or both?
> * Is there a specific .pt3 file this is happening with?
> * Does it stop entirely, or pause then continue/restart?
> * After it stops will RESUME PT3 cause it to continue where it left off?

- Real hardware
- Seems like any PT3 (I have tried half a dozen so far)
- Yes, it stops entirely
- RESUMEPT3 starts the tune from the beginning (although its seems to do that even if you use stoptp3)

**Comment by RevCurtisP** [comment]
Example files that ended abruptly: `Crazy.pt3` and `termnatr.pt3`. 
Loaded both files into Vortex Tracker in Windows.
Verified that when played on Aq+, songs ended at actual end point of file.

**Comment by RevCurtisP** [comment]
**Resolution:** PLAY PT3 working correctly, PT3 files may be corrupted.
