### ISSUE TITLE
ESP:Settings

### ISSUE THREAD

**Issue by MackW** [fvdhoef/aquarius-plus#83]
Hostname (as in name at the top) is displayed incorrectly (even after power cycle)
(although I'm not sure it is the hostname anymore - just a string?) 
![image](https://github.com/user-attachments/assets/fe1ac53e-8cf5-47b7-b078-d3cd98ff2d16)

**Comment by fvdhoef** [comment]
'Name:' at the top is actually referring to the internal name of the ESP32 firmware. Your current hostname is shown when running the hostname command.
