### ISSUE TITLE
Add debugger keys

### ISSUE THREAD

**Issue by paulscottrobson** [fvdhoef/aquarius-plus#88]
I would like the option (command line switchable) for the unused function keys (F7-F12) to be able to operate the buttons in the CPU State window.

I would also like to volunteer myself to do this :) I have looked at the code and can see how it can be done (I think !) without having, I believe, any other effect on the emulator, (extracting the code attached to the buttons to seperate methods and invoking them from the keyboard input queue)

There doesn't appear to be a simple way of doing this in the way that you can bind a button to a menu action or button in many GUIs. 

If you are okay with this, I will fork the repo (or you can add me as a collaborator, as you wish) and do the work for review via the usual system.

**Comment by fvdhoef** [comment]
I was working on the emulator myself to fix some Linux issues, so I have also picked up your request.
Whenever the CPU state window is visible the following keyboard shortcuts are available (you can also see these by hovering the buttons):
- Halt: Shift-F5
- Step Into: F11
- Step Over: F10
- Step Out: Shift-F10
- Go: F5
(I have based these on the Visual Studio shortcuts)

This will be available in the next release, but for now I have updated the development build, which you can find here: https://github.com/fvdhoef/aquarius-plus/releases/tag/V1.dev

**Comment by paulscottrobson** [comment]
Excellent :)
